import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "SR Eco Park",
  description: "Generated by create next app",
  icons: {
    icon: [
      { rel: "icon", type: "image/png", url: "/images/favicon.png" }
    ]
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
